@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package droidicus.aquaregia.api.capability.hiddenblockrevealer;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
