@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package droidicus.aquaregia.inventory.itemhandler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
