@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package droidicus.aquaregia.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
